
const icons={home:'<path d="M3 10l9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',projects:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',bookings:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v5m10-5v5M3 11h18m-13 4h3m3 0h3"/>',member:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0116 0v2"/>',wallet:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 9h18m-5 5h5"/>',points:'<path d="M12 3l3 6 6 1-4 5 1 6-6-3-6 3 1-6-4-5 6-1z"/>',gift:'<rect x="3" y="9" width="18" height="4"/><path d="M5 13v8h14v-8M12 9v12"/><path d="M12 9C3 9 5 1 9 4l3 5c9 0 7-8 3-5z"/>'};
const icon=n=>`<span class="icon"><svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.gift}</svg></span>`;
const projects=[{id:1,cat:'美容护肤',name:'水润修护面部护理',desc:'清洁 · 补水 · 舒缓护理',price:198,old:268,duration:60},{id:2,cat:'美甲美睫',name:'纯色凝胶美甲',desc:'修形 · 基础护理 · 纯色上色',price:128,old:168,duration:60},{id:3,cat:'美发造型',name:'精剪洗护造型',desc:'洗护 · 定制造型 · 吹整',price:98,old:128,duration:45},{id:4,cat:'身体护理',name:'肩颈舒缓护理',desc:'温热放松 · 肩颈护理',price:168,old:228,duration:45},{id:5,cat:'美甲美睫',name:'自然款单根美睫',desc:'款式沟通 · 单根嫁接',price:228,old:298,duration:90},{id:6,cat:'美容护肤',name:'基础清洁护理',desc:'卸妆 · 深层清洁 · 保湿',price:128,old:168,duration:45}];
let state={balance:0,points:0,bookings:[],moneyLog:[],pointLog:[],coupons:[]},page='home',category='全部',draft={},recharge=500,toastTimer;
const money=n=>Number(n).toFixed(2);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notify(s){const t=document.getElementById('toast');t.textContent=s;t.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add('hidden'),2600)}
function go(p){page=p;render();window.scrollTo({top:0,behavior:'instant'})}
function nav(){document.getElementById('nav').innerHTML=[['home','首页'],['projects','项目'],['bookings','预约'],['member','我的']].map(([p,t])=>`<button class="${page===p||(p==='member'&&['wallet','points','coupons','store','records'].includes(page))?'active':''}" ${page===p?'aria-current="page"':''} onclick="go('${p}')">${icon(p)}<span>${t}</span></button>`).join('')}
function card(p){return `<article class="project"><div class="number">0${p.id}</div><div class="body"><span class="badge">${p.cat}</span><h3>${p.name}</h3><p class="sub">${p.duration} 分钟 · ${p.desc}</p><div><span class="price"><small>¥</small>${p.price}</span><span class="old">¥${p.old}</span></div></div><button class="pill" onclick="detail(${p.id})">查看</button></article>`}
function home(){return `<div class="row"><div><div class="eyebrow">YUEJI BEAUTY</div><h2>今天，也好好照顾自己</h2></div></div><p class="sub">美容 · 美甲美睫 · 美发 · 身体护理</p><div class="hero"><div class="hero-copy"><span class="eyebrow" style="color:#f4c9dc">YOUR BEAUTY MOMENT</span><h2>留一点时间<br>给自己</h2><p>选一项喜欢的护理，预约你的时刻。</p><button onclick="go('projects')">立即预约</button></div></div><div class="quick">${[['projects','项目价格'],['wallet','会员储值'],['points','积分中心'],['activities','最新活动']].map(([p,t])=>`<button onclick="go('${p}')">${icon(p)}${t}</button>`).join('')}</div><section class="section"><div class="row section-title"><h2>本月小惊喜</h2><button class="link" onclick="go('activities')">查看活动</button></div><div class="promo"><span class="badge">新客体验</span><p><strong>水润修护护理 ¥198</strong></p><p>60 分钟，给肌肤一段放松的时间。</p><button class="pill" onclick="detail(1)">查看体验项目</button></div></section><section class="section"><div class="row section-title"><h2>人气项目</h2><button class="link" onclick="go('projects')">全部项目</button></div><div class="projects">${projects.slice(0,3).map(card).join('')}</div></section><section class="panel"><div class="row"><h3>悦己美学 · 单店</h3><button class="link" onclick="go('store')">门店详情</button></div><p class="sub">每日 10:00–21:00 · 到店前建议提前预约</p></section><p class="bottom-note">悦己，从这一刻开始。</p>`}
function projectPage(){return `<h2>找到适合你的项目</h2><p class="sub">明码标价 · 免费预约 · 到店结算</p><div class="chips">${['全部','美容护肤','美甲美睫','美发造型','身体护理'].map(c=>`<button class="${category===c?'active':''}" onclick="category='${c}';render()">${c}</button>`).join('')}</div><div class="projects">${projects.filter(p=>category==='全部'||p.cat===category).map(card).join('')}</div>`}
function detail(id){draft={project:id};go('detail')}
function detailPage(){const p=projects.find(p=>p.id===draft.project);return `<button class="back" onclick="go('projects')">返回项目</button><div class="eyebrow">${p.cat}</div><h2>${p.name}</h2><p class="sub">${p.desc}</p><div class="panel"><span class="price" style="font-size:34px"><small>¥</small>${p.price}</span><span class="old">¥${p.old}</span><p class="sub">参考时长 ${p.duration} 分钟 · 到店结算</p></div><div class="panel"><h3>服务内容</h3><p class="sub" style="margin-top:10px">${p.desc.split(' · ').join('、')}。服务前会沟通你的需求与偏好，实际效果因个人情况而异。</p></div><div class="panel"><h3>预约须知</h3><p class="sub" style="margin-top:10px">预约无需预付费用。请提前 10 分钟到店；需要调整安排时，可在预约记录中取消后重新预约。项目价格为演示价格。</p></div><button class="primary full" onclick="startBooking(${p.id})">预约此项目</button>`}
function dates(){return Array.from({length:4},(_,i)=>{let d=new Date();d.setDate(d.getDate()+i);return {value:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,label:i===0?'今天':i===1?'明天':`${d.getMonth()+1}/${d.getDate()}`}})}
function staffFor(id){return id===3?['阿森 · 发型师','小雨 · 发型师']:id===2||id===5?['小夏 · 美甲美睫师','可可 · 美甲美睫师']:['安安 · 护理师','小雅 · 护理师']}
function startBooking(id){draft={project:id,date:dates()[0].value,staff:staffFor(id)[0],time:'',name:'',phone:''};go('bookingForm')}
function blocked(t){const minutes=t.split(':').map(Number),start=minutes[0]*60+minutes[1];const p=projects.find(p=>p.id===draft.project);if(draft.date===dates()[0].value&&start<=new Date().getHours()*60+new Date().getMinutes())return true;return state.bookings.some(b=>b.status==='已预约'&&b.date===draft.date&&b.staff===draft.staff&&start<b.start+b.duration&&start+p.duration>b.start)}
function formPage(){const p=projects.find(p=>p.id===draft.project);return `<button class="back" onclick="go('detail')">返回项目</button><h2>预约你的变美时刻</h2><div class="panel"><h3>${p.name}</h3><p class="sub">${p.duration} 分钟 · ¥${p.price} · 到店结算</p></div><section class="section"><h3>选择服务人员</h3><div class="choices" style="grid-template-columns:1fr 1fr">${staffFor(p.id).map(s=>`<button class="choice ${draft.staff===s?'active':''}" onclick="draft.staff='${s}';draft.time='';render()">${s}</button>`).join('')}</div></section><section class="section"><h3>选择日期</h3><div class="choices dates">${dates().map(d=>`<button class="choice ${draft.date===d.value?'active':''}" onclick="draft.date='${d.value}';draft.time='';render()">${d.label}<br><span class="sub">${d.value.slice(5)}</span></button>`).join('')}</div></section><section class="section"><h3>选择时间</h3><div class="choices">${['10:00','11:30','13:00','14:30','16:00','17:30','19:00'].map(t=>`<button class="choice ${draft.time===t?'active':''}" ${blocked(t)?'disabled':''} onclick="draft.time='${t}';render()">${t}${blocked(t)?'<br><small>不可预约</small>':''}</button>`).join('')}</div></section><form onsubmit="submitBooking(event)"><label for="customer">称呼</label><input id="customer" name="customer" placeholder="请输入你的称呼" value="${esc(draft.name||'')}" required maxlength="20" oninput="draft.name=this.value"><label for="phone">联系电话</label><input id="phone" name="phone" type="tel" inputmode="numeric" placeholder="请输入 11 位手机号码（演示可用虚拟号码）" value="${esc(draft.phone||'')}" pattern="1[0-9]{10}" maxlength="11" required oninput="draft.phone=this.value"><div class="notice">本次无需付款。此原型只在当前页面模拟预约，不会通知门店。</div><button type="submit" class="primary full">确认免费预约</button></form>`}
function submitBooking(e){e.preventDefault();if(!draft.time)return notify('请选择预约时间');if(!draft.name.trim()||!/^1\d{10}$/.test(draft.phone))return notify('请填写称呼和有效手机号码');if(blocked(draft.time))return notify('该时段已不可预约，请重新选择');const p=projects.find(p=>p.id===draft.project);state.bookings.unshift({...draft,id:Date.now(),status:'已预约',start:Number(draft.time.slice(0,2))*60+Number(draft.time.slice(3)),duration:p.duration});go('success')}
function successPage(){return `<div class="success"><div class="check">✓</div><h2>预约已记录</h2><p class="sub">这是一次模拟预约，没有发送给真实门店。</p></div><div class="panel"><h3>${projects.find(p=>p.id===draft.project).name}</h3><div class="line-item"><span>时间</span>${draft.date} ${draft.time}</div><div class="line-item"><span>服务人员</span>${draft.staff}</div><div class="line-item"><span>付款方式</span>到店结算</div></div><button class="primary full" onclick="go('bookings')">查看我的预约</button>`}
function bookingPage(){return `<h2>我的预约</h2><p class="sub">安排好时间，安心来变美。</p>${state.bookings.length?state.bookings.map(b=>`<article class="panel booking"><div class="row"><span class="badge">${b.status}</span><span class="sub">免费预约</span></div><h3>${projects.find(p=>p.id===b.project).name}</h3><p class="sub">${b.date} ${b.time} · ${b.duration} 分钟</p><p class="sub">${b.staff}</p>${b.status==='已预约'?`<div class="actions"><button class="pill" onclick="cancelBooking(${b.id})">取消预约</button><button class="pill" onclick="showDialog('到店结算','实际消费后由店家核销、确认金额并扣除储值余额和发放积分。顾客端不能自行确认消费。')">结算说明</button></div>`:''}</article>`).join(''):`<div class="empty">${icon('bookings')}<h3>还没有预约</h3><p class="sub">选一项喜欢的服务，留点时间给自己。</p><button class="primary full" onclick="go('projects')">浏览项目并预约</button></div>`}`}
function showDialog(title,body,action){const d=document.getElementById('dialog');d.innerHTML=`<h3>${esc(title)}</h3><p>${esc(body)}</p><div class="actions"><button class="pill" onclick="document.getElementById('dialog').close()">${action?'暂不':'知道了'}</button>${action?'<button id="confirmAction" class="primary">确认</button>':''}</div>`;if(action)d.querySelector('#confirmAction').onclick=()=>{d.close();action()};d.showModal()}
function cancelBooking(id){showDialog('取消这次预约？','取消后该时段会释放，你可以重新选择时间预约。',()=>{state.bookings.find(b=>b.id===id).status='已取消';render();notify('预约已取消')})}
function memberPage(){return `<div class="row"><div><div class="eyebrow">MY BEAUTY CLUB</div><h2>我的会员中心</h2></div><span class="badge">已入会</span></div><div class="member"><div class="row"><span>悦己会员</span><span class="badge">普通会员</span></div><div class="member-title">欢迎你，新朋友</div><p class="sub">首次登录即可成为会员</p><div class="stats"><button onclick="go('wallet')"><strong>¥${money(state.balance)}</strong><span>储值余额</span></button><button onclick="go('points')"><strong>${state.points}</strong><span>可用积分</span></button></div></div><div class="quick">${[['bookings','我的预约'],['wallet','会员储值'],['points','积分中心'],['coupons','优惠券']].map(([p,t])=>`<button onclick="go('${p}')">${icon(p)}${t}</button>`).join('')}</div><div class="menu"><button onclick="go('records')">账户流水<small>充值与积分明细</small></button><button onclick="showDialog('普通会员权益','可预约全部项目、查看活动和会员账户。演示规则：完成消费每满 1 元获得 1 积分；充值不赠送积分，积分可兑换指定优惠券。')">会员权益<small>查看规则</small></button><button onclick="go('store')">门店信息<small>地址与营业时间</small></button><button onclick="showDialog('联系门店','此处将接入门店电话或微信客服。当前没有配置真实联系方式。')">联系门店<small>咨询服务</small></button><button onclick="resetDemo()">重置演示<small>清空本次体验数据</small></button></div><div class="notice">演示账户已自动开通。初始积分与余额为零，刷新页面会重置本次体验。</div>`}
function walletPage(){return `<button class="back" onclick="go('member')">返回会员中心</button><h2>会员储值</h2><div class="panel"><p class="sub">可用余额（演示）</p><div class="balance">¥${money(state.balance)}</div><p class="sub">本金与赠送金分开记账 · 本次仅模拟展示</p></div><section class="section"><h3>选择充值金额</h3><div class="choices">${[300,500,1000].map(n=>`<button class="choice ${recharge===n?'active':''}" onclick="recharge=${n};render()"><strong>¥${n}</strong><br><small>${n===300?'无赠送':n===500?'赠 ¥30':'赠 ¥100'}</small></button>`).join('')}</div></section><div class="notice">演示优惠：充 500 赠 30，充 1000 赠 100。赠送金仅限消费，不可提现。正式规则由门店设定。</div><button class="primary full" onclick="topup()">模拟充值 ¥${recharge}</button><p class="bottom-note">不会唤起微信支付，不产生真实扣款。</p><section class="section"><h3>充值记录</h3>${state.moneyLog.length?state.moneyLog.map(l=>`<div class="panel"><div class="row"><strong>充值 ¥${l.principal}</strong><strong style="color:var(--accent)">+¥${l.total}</strong></div><p class="sub">赠送 ¥${l.gift} · ${l.time}</p></div>`).join(''):'<div class="panel sub">暂无充值记录</div>'}</section>`}
function topup(){const n=recharge,gift=n===500?30:n===1000?100:0;showDialog('确认模拟充值？',`演示充值 ¥${n}，赠送 ¥${gift}，余额将增加 ¥${n+gift}。不产生实际支付。`,()=>{state.balance+=n+gift;state.moneyLog.unshift({principal:n,gift,total:n+gift,time:new Date().toLocaleString('zh-CN')});render();notify('模拟充值成功，余额已更新')})}
function pointsPage(){return `<button class="back" onclick="go('member')">返回会员中心</button><h2>积分中心</h2><div class="panel"><p class="sub">可用积分</p><div class="balance">${state.points}<small style="font-size:16px;color:var(--muted)"> 积分</small></div><p class="sub">消费完成后累计，充值不累计积分。</p></div><section class="section"><h3>积分好礼</h3>${[{id:'coupon20',name:'20 元护理优惠券',cost:200},{id:'coupon50',name:'50 元护理优惠券',cost:500}].map(r=>`<div class="reward">${icon('gift')}<div class="body"><h3>${r.name}</h3><p class="sub">${r.cost} 积分 · 满 ${r.cost===200?198:398} 元可用</p></div><button class="pill" ${state.points<r.cost?'disabled':''} onclick="redeem('${r.id}')">兑换</button></div>`).join('')}</section><div class="notice">为了体验兑换流程，可加入一笔模拟消费积分。正式小程序的积分由店家核销消费后发放。</div><button class="pill full" onclick="addPoints()">体验：模拟消费 ¥300，获得 300 积分</button><section class="section"><h3>积分明细</h3>${pointRecords()}</section>`}
function addPoints(){state.points+=300;state.pointLog.unshift({label:'模拟消费 ¥300',amount:300,time:new Date().toLocaleString('zh-CN')});render();notify('演示积分 +300')}
function redeem(id){const cost=id==='coupon20'?200:500,name=id==='coupon20'?'20 元护理优惠券':'50 元护理优惠券';if(state.points<cost)return notify('积分不足');showDialog('兑换优惠券？',`将扣除 ${cost} 积分，兑换${name}。`,()=>{if(state.points<cost)return notify('积分不足');state.points-=cost;state.coupons.unshift({name,min:cost===200?198:398,id:Date.now()});state.pointLog.unshift({label:'兑换'+name,amount:-cost,time:new Date().toLocaleString('zh-CN')});render();notify('兑换成功，可在我的优惠券中查看')})}
function pointRecords(){return state.pointLog.length?state.pointLog.map(l=>`<div class="panel"><div class="row"><strong>${l.label}</strong><strong style="color:var(--accent)">${l.amount>0?'+':''}${l.amount}</strong></div><p class="sub">${l.time}</p></div>`).join(''):'<div class="panel sub">暂无积分明细</div>'}
function couponsPage(){return `<button class="back" onclick="go('member')">返回会员中心</button><h2>我的优惠券</h2><p class="sub">到店结算时向店家出示，由店家核销。</p>${state.coupons.length?state.coupons.map(c=>`<div class="promo section"><h3>${c.name}</h3><p>满 ¥${c.min} 可用 · 护理项目专享</p><span class="badge">未使用 · 演示券</span></div>`).join(''):'<div class="empty">'+icon('gift')+'<h3>暂无优惠券</h3><p class="sub">积攒消费积分，兑换你喜欢的好礼。</p><button class="primary full" onclick="go(\'points\')">前往积分中心</button></div>'}`}
function activitiesPage(){return `<button class="back" onclick="go('home')">返回首页</button><h2>最新活动</h2><p class="sub">以下为样例活动，可替换成门店真实内容。</p><div class="activity"><div class="eyebrow" style="color:#f6c9da">NEW CLIENT SPECIAL</div><h2>第一次见面<br>从一场好护理开始</h2><p class="sub">新客水润修护面部护理 · ¥198 / 60 分钟</p><button class="primary full" onclick="detail(1)">查看项目并预约</button></div><div class="promo section"><span class="badge">会员储值礼</span><p><strong>充 ¥500 赠 ¥30</strong></p><p>充 ¥1000 赠 ¥100，赠送金限店内消费。</p><button class="pill" onclick="go('wallet')">查看模拟储值</button></div><div class="panel"><h3>活动说明</h3><p class="sub" style="margin-top:10px">演示活动长期展示。实际有效期、参加条件及优惠能否叠加，正式上线前由门店确认。</p></div>`}
function storePage(){return `<button class="back" onclick="go('member')">返回会员中心</button><div class="eyebrow">OUR STUDIO</div><h2>悦己美学</h2><p class="sub">综合美业 · 单门店</p><div class="hero"><div class="store-placeholder">门店实景照片 · 待替换</div></div><div class="store-grid"><div class="panel"><strong>营业时间</strong><span class="sub">每日 10:00–21:00</span></div><div class="panel"><strong>预约方式</strong><span class="sub">在线预约，到店结算</span></div></div><div class="panel"><h3>门店地址</h3><p class="sub" style="margin-top:8px">待填写真实门店地址</p><button class="pill full" onclick="showDialog('门店导航','填写真实门店地址后，这里可以接入微信地图导航。当前没有真实地图目的地。')">查看导航入口</button></div><button class="primary full" onclick="showDialog('联系门店','待配置真实门店联系电话或微信客服。')">联系门店</button>`}
function recordsPage(){return `<button class="back" onclick="go('member')">返回会员中心</button><h2>账户流水</h2><div class="menu"><button onclick="go('wallet')">储值明细<small>${state.moneyLog.length} 笔记录</small></button><button onclick="go('points')">积分明细<small>${state.pointLog.length} 笔记录</small></button></div><div class="panel"><h3>消费记录</h3><p class="sub">暂无真实消费记录。到店消费完成后，店家核销记录将在此展示。</p></div>`}
function resetDemo(){showDialog('重置本次体验？','将清空当前页面的预约、储值、积分和优惠券演示数据。',()=>{state={balance:0,points:0,bookings:[],moneyLog:[],pointLog:[],coupons:[]};go('home');notify('演示数据已重置')})}
function render(){nav();const pages={home,projects:projectPage,detail:detailPage,bookingForm:formPage,success:successPage,bookings:bookingPage,member:memberPage,wallet:walletPage,points:pointsPage,coupons:couponsPage,activities:activitiesPage,store:storePage,records:recordsPage};document.getElementById('view').innerHTML=pages[page]();}
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'navigate_beauty_prototype',description:'Navigate to a customer prototype view. Does not create a booking or payment.',inputSchema:{type:'object',properties:{page:{type:'string',enum:['home','projects','bookings','member','wallet','points','activities']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['home','projects','bookings','member','wallet','points','activities'].includes(input.page))throw Error('Invalid page');go(input.page);return{page}}})).catch(()=>{})}catch(e){}}
